name: Test de météorologie

on: 
  push: 
    branches: 
      - master
  pull_request:
    branches:
      - master

jobs:
  test-meteo:
    runs-on: windows-latest

    steps:
    - name: Get le code
      uses: actions/checkout@v2

    - name: Installer Python
      uses: actions/setup-python@v2
      with: 
        python-version: '3.x'
      
    - name: Installer les dépendances
      run: |
        python -m pip install --upgrade pip
        pip install requests python-dotenv

    - name: Test de l'api de météo
      run: |
        $url = "https://api.openweathermap.org/data/2.5/weather?q=Paris&appid=${{ secrets.API_KEY }}&units=metric"
        $response = Invoke-RestMethod -Uri $url -Method Get
        $response | ConvertTo-Json -Depth 3

    - name: Test de Pays Togo
      run: |
        $url = "http://localhost:5001/submit"
        $body = "pays=France"
        $headers = @{ "Authorization" = "Bearer ${{ secrets.API_KEY }}" }
        $response = Invoke-RestMethod -Uri $url -Method POST -Body $body -Headers $headers
        Write-Output "Response: $($response)"
        if ($response.StatusCode -eq 200) {
            Write-Host "Test réussi"
        } else {
            Write-Host "Test échoué"
        }
      
    - name: Stop server
      run: |
        Stop-Process -Name "python" -Force  # Assurez-vous que le nom du processus est correct
