name: Test Pays

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test_pays:
    runs-on: windows-latest  # Utilisation de Windows au lieu d'Ubuntu

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests python-dotenv  # Installation des bibliothèques nécessaires

    - name: Start server
      run: |
        Start-Process -NoNewWindow -FilePath "python" -ArgumentList "expose_py.py"
        Start-Sleep -Seconds 5  # Pause pour laisser le serveur démarrer
      shell: powershell

    - name: Test pays France
      run: |
        Invoke-WebRequest -Uri "http://127.0.0.1:5001/soumettre" -Method POST -Body "pays=France" -ContentType "application/x-www-form-urlencoded"
      shell: powershell

    - name: Stop server
      run: Get-Process python | Stop-Process -Force
      shell: powershell
